### ISSUE TITLE
Elegir repositorio

### ISSUE THREAD

**Issue by jlgarridol** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#1]
Buscar entre los distintos gestores de repositorio cual es el que mejor se adapta a nuestras necesidad

**Comment by Josemi** [comment]
Yo elegiría GitKraken, hay un trabajo del otro año en Interacción Hombre-Máquina muy muy bueno de este GitKraken.

**Comment by jlgarridol** [comment]
@Josemi Es una buena idea pero solo valdría en local, tenemos que encontrar una remota para poder comunicarnos entre nosotros. Si a ti te gusta gitkraken (personalmente prefiero la consola) sin problemas, ya que solo lo tendrás tú.

**Comment by jlgarridol** [comment]
Creo que el mejor va a ser GitHub, ya que el proyecto es open source y no necesitamos nada privado. Además es el sitio más popular por lo que si alguien quiere colaborar de manera externa lo tenga más fácil. ¿Cómo lo veis?

**Comment by MarinaGarme** [comment]
Perfecto. Además es lo que nos toca hacer.
