### ISSUE TITLE
Investigar Background substraction

### ISSUE THREAD

**Issue by jlgarridol** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#13]
- [x] http://docs.opencv.org/master/db/d5c/tutorial_py_bg_subtraction.html
- [x] http://docs.opencv.org/3.1.0/d1/dc5/tutorial_background_subtraction.html
- [x] Cap6 de OpenCV 3.0 Computer Vision with Java

**Comment by MarinaGarme** [comment]
Terminado y documentado: https://github.com/davidmigloz/go-bees/wiki/3_ConceptosTe%C3%B3ricos#2%C2%BA-substracci%C3%B3n-del-fondo
