### ISSUE TITLE
Leer video desde archivo en la app

### ISSUE THREAD

**Issue by Josemi** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#17]
Añadir a la app la opción de seleccionar si se quiere abrir la cámara o tomar como entrada un archivo de video.

**Comment by jlgarridol** [comment]
VideoCapture de OpenCV no posee ffmpeg backend en Android -> No es posible leer videos desde archivo con OpenCV4Android.

**Comment by jlgarridol** [comment]
Abandono esta opción. Para agilizar el desarrollo de los algoritmos de visión artificial voy a desarrollar una aplicación en Java en donde si está soportada la opción de leer un archivo de vídeo. El portar los algoritmos posteriormente a Android tomando como entrada la cámara debería ser una tarea trivial (Confíamos).
