### ISSUE TITLE
Investigar algoritmos de motion detection and tracking en OpenCV

### ISSUE THREAD

**Issue by MarinaGarme** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#20]
Investigar algoritmos de motion detection and tracking en OpenCV

**Comment by jlgarridol** [comment]
### 1º Background subtraction

Realizar esta fase solo si es estrictamente necesaria (es costosa).

  * BackgroundSubtractorMOG Docs | Tutorial

### 2º Detección de bordes

Probar si el resaltado de los bordes ayuda en la siguiente fase.

    * Sobel Docs | Tutorial

### 3º Detección de abejas

    * SimpleBlobDetector Docs | Tutorial

### 4º Tracking

    * KLT Tracker Docs | Tutorial

Otros algorithmos de tracking (MIL, BOOSTING, MEDIANFLOW, TLD, KCF).

*TLD no va a resultar porque es muy pesado.
