### ISSUE TITLE
Lección 1 curso Android

### ISSUE THREAD

**Issue by edzlo** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#21]
https://www.udacity.com/course/new-android-fundamentals--ud851

Lesson 1: Create Project Sunshine with a Simple UI (5-8 hrs)

Start by installing Android Studio, you’ll create your first project with a simple list-based user interface. You'll then build and deploy it to virtual and actual devices. You’ll also discover what makes mobile - and Android in particular - a unique environment for app development.

Android Studio, Gradle, and debugging tools
User Interface and Layout managers
ListViews and Adapters

**Comment by jlgarridol** [comment]
Leido
