### ISSUE TITLE
Leer cap. 3 libro Android OpenCV

### ISSUE THREAD

**Issue by jlgarridol** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#23]
Chapter 3, Applying Image Effects, explores OpenCV's functionality to manipulate color channels and neighborhoods of pixels. The Apache Commons Math library is also introduced. We expand our app to include channel-mixing filters, "curve" filters, and a filter that darkens edges.

**Comment by Josemi** [comment]
Terminado pero con problemas.
App desarrollada: https://github.com/davidmigloz/second-sight/

1. Problemas de compatibilidad con la implementación de OpenCV en dispositivos con API < 21. No he encontrado solución por el momento. He lanzando una pregunta en StackOverflow:
ClassNotFoundException: android.hardware.camera2.CameraAccessException with OpenCV 3.1.0

2. Problemas al aplicar filtros convolution flters y mixing color channels:

> 09-29 14:57:17.719 16327-16581/com.davidmiguel.secondsight A/libc: Fatal signal 7 (SIGBUS), code 1, fault addr 0xb36eb879 in tid 16581 (Thread-3759)
