### ISSUE TITLE
Postprocesado imagen 

### ISSUE THREAD

**Issue by edzlo** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#24]
Investigar técnicas de postprocesado de la imagen después de aplicar la extracción del fondo para mejorar sus resultados.

http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_morphological_ops/py_morphological_ops.html

**Comment by Josemi** [comment]
Se obtienen mejores resultados realizando los siguientes pasos:
1. Conversión a escala de grises (mejora eficiencia).
2. Ecualización del historiograma (mejora contraste).
3. Desenfoque gausiano (reduce ruido).

Las tres fases han sido implementadas en la DevelopmentPlatform.
