### ISSUE TITLE
Grabación de vídeos

### ISSUE THREAD

**Issue by jlgarridol** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#25]
Grabar vídeos en el colmenar intentando recoger todas las situaciones que se podrá encontrar la app (sombras, solapamiento de abejas...).

**Comment by Josemi** [comment]
He realizado las grabaciones desde dos posiciones, una frontal y otra cenital con un cartón blanco en el suelo. Creo que con la segunda obtendremos mejores resultados, ya que evitamos que haya grandes diferencias de perspectiva en las abejas y además la superficie del cartón facilitará la extracción del fondo.

![](https://cloud.githubusercontent.com/assets/6546265/18811793/b19f1f1c-82bd-11e6-9776-82df97321fff.jpg)

![](https://cloud.githubusercontent.com/assets/6546265/18811794/b27307d2-82bd-11e6-8e82-3cd0ce318aa8.jpg)

**Comment by Josemi** [comment]
He subido todos los vídeos a YouTube y he creado una página en la wiki para agruparlos:
https://github.com/davidmigloz/go-bees/wiki/Video-Dataset

**Comment by jlgarridol** [comment]
Una tarde currada sin duda, los videos geniales. Vamos a cerrar esto y casi terminar el sprint
