### ISSUE TITLE
Diseñar logo

### ISSUE THREAD

**Issue by jlgarridol** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#26]
Diseñar un logo representativo para la app.

**Comment by Josemi** [comment]
El logo quedaría tal que así:

![](https://cloud.githubusercontent.com/assets/6546265/18811869/86df7242-82c0-11e6-9d75-244a6b40a3a7.jpg)

**Comment by Josemi** [comment]
Si veis que se puede cambiar algo para mejorarlo avisadme
