### ISSUE TITLE
Dar soporte a las fases del procesado en DevelopmentPlatform

### ISSUE THREAD

**Issue by MarinaGarme** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#28]
Permitir visualizar y parametrizar cada una de las distintas fases del procesado (preprocesado, background subtraction, postprocesado...) en la DevelopmentPlatform desarrollada en Java.

**Comment by edzlo** [comment]
![e50d0aa2-90e7-11e6-86a2-cf9953ca917f](https://user-images.githubusercontent.com/25634633/32826155-9c234150-c9e7-11e7-8230-284b7fb9a5df.gif)


Plataforma desarrollada. Catacterísticas:

- Cargar vídeo con FileChooser.
- Reproductor de vídeo con controles.
- Una pestaña por fase con controles de los parámetros de los diferentes algoritmos.
- Permite realizar modificaciones de los parámetros en tiempo real.
