### ISSUE TITLE
Elegir IDE

### ISSUE THREAD

**Issue by edzlo** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#3]
**_Elegir el Entorno de Desarrollo Integrado_**

**Comment by Josemi** [comment]
Yo voto por Eclipse ya que es lo que hemos utilizado en diferentes asignaturas, aunque cada uno podría utilizar el que más le guste mientras no haya conflicto

**Comment by MarinaGarme** [comment]
Yo también voto por Eclipse, aunque si queréis utilizar otro personal, mientras no provoque problemas.

**Comment by jlgarridol** [comment]
Si el .gitignore elimina las configuraciones personales usad el que queráis aunque Eclipse si que nos dará más versatilidad al ser libre

**Comment by edzlo** [comment]
**Herramienta elegida:**
Eclipse, puesto que por votación es la elegida y en la que hemos trabajo todos en cursos anteriores.
Sin embargo, se podrá utilizar cualquier otro como @JoseluCross ha indicado en un comentario.
