### ISSUE TITLE
Preprocesado imagen 

### ISSUE THREAD

**Issue by MarinaGarme** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#32]
Investigar que algoritmos se pueden aplicar antes de la extracción de fondo para mejorar sus resultados.

**Comment by edzlo** [comment]
Considerar las siguientes fases:

1. Conversión a escala de grises (mejora eficiencia).
2. Ecualización del historiograma (mejora contraste).
3. Desenfoque gausiano (reduce ruido).

**Comment by edzlo** [comment]
Las tres fases han sido implementadas en la DevelopmentPlatform.
