### ISSUE TITLE
ClassNotFoundException con la API camera2

### ISSUE THREAD

**Issue by jlgarridol** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#37]
Descripción del problema en StackOverflow:
ClassNotFoundException: android.hardware.camera2.CameraAccessException with OpenCV 3.1.0

A partir de la issue #23 de @Josemi

**Comment by Josemi** [comment]
Problema resulto deshabilitando Instant Run en Android Studio.
File > Settings > Build, Execution, Deployment > InstantRun and uncheck Enable Instant Run to hot swap code....

**Comment by jlgarridol** [comment]
Gracias
