### ISSUE TITLE
Elegir herramienta de gestión de proyecto

### ISSUE THREAD

**Issue by jlgarridol** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#4]
Antes de poder elegir que herramienta es necesario #1

**Comment by jlgarridol** [comment]
Según elijamos en #1 esto variará pero si decidís quedarse con GitHub podemos usar ZenHub de manera interna pero si no lo veís en GitLab tiene por defecto un sistema para la gestión de boards

**Comment by jlgarridol** [comment]
Tras elegir GitHub podemos utilizar ZenHub aunque si queréis utilizar otra offline o sobre otra plataforma decidid

**Comment by Josemi** [comment]
ZenHub parece bastante útil. Yo elegiría ZenHub.

**Comment by edzlo** [comment]
ZenHub sin duda.

**Comment by jlgarridol** [comment]
Lo doy por cerrado
