### ISSUE TITLE
Testar algoritmos

### ISSUE THREAD

**Issue by jlgarridol** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#45]
Crear unit test para cada algoritmo.

**Comment by MarinaGarme** [comment]
Para testear los algoritmos que utilizan OpenCV en Travis, este tiene que:

Descargar repositorio de OpenCV.
Compilar OpenCV.
Obtener la librería nativa.
Añadir su ruta al path (LD_LIBRARY_PATH).
Una vez completados estos pasos (alrededor de 5 minutos) ya puede lanzar los test unitarios.

Problemas encontrados:

- Al no lanzar emulador para los test unitarios no disponíamos de OpenCV Manager, por lo tanto la librería de OpenCV había que cargarla de manera estática.
- Muchos intentos hasta conseguir que OpenCV funcionara correctamente en Travis.
- Si cada test suite cargaba la librería de OpenCV (System.loadLibrary()) se obtenía la excepción UnsatisfiedLinkError.
- Si se creaba un test suite solo para controlar el orden de los demás y en este se inicializaba la librería se seguía obteniendo la misma excepción.
- Finalmente se han agrupado todos los tests de las clases que usan OpenCV en un solo test suite.
