### ISSUE TITLE
Probar app contra pantalla

### ISSUE THREAD

**Issue by jlgarridol** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#48]

**Comment by MarinaGarme** [comment]
Se probó la app grabando contra una pantalla y se obtuvieron los siguientes resultados:

A fps reales del video, por cada exposición de la cámara recogía varios fotogramas del vídeo, por lo que salían abejas duplicadas.
El problema se solventó reduciendo la velocidad de reproducción del vídeo.
La app cuenta correctamente el número de abejas que aparecen en la pantalla.
