### ISSUE TITLE
Elegir herramienta de testing

### ISSUE THREAD

**Issue by MarinaGarme** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#5]
Herramientas elegidas para el test de la práctica

**Comment by jlgarridol** [comment]
Para los test unitarios los unnitest están muy bien, JUnit para java es de lo mejorcito

**Comment by Josemi** [comment]
Dado que es Java, yo elegiría JUnit que ya hemos trabajado con ello

**Comment by MarinaGarme** [comment]
Entonces nos quedamos con JUnit, ¿alguien en contra?

**Comment by MarinaGarme** [comment]
JUnit, un conjunto de clases (framework) que permite realizar la ejecución de clases Java de manera controlada, para poder evaluar si el funcionamiento de cada uno de los métodos de la clase se comporta como se espera.
