### ISSUE TITLE
Volcar en un log los datos de desviación del algoritmo

### ISSUE THREAD

**Issue by Josemi** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#51]
Volcar en un log los datos de desviación del algoritmo

**Comment by jlgarridol** [comment]
Volcados los algoritmos hasta ahora, pero de momento no la cierro hasta concluir el resto de algoritmos

**Comment by jlgarridol** [comment]
La devuelvo a Backlog

**Comment by jlgarridol** [comment]
Tras haber terminado todas las herramientas incluyo en el log los nuevos resultados

**Comment by jlgarridol** [comment]
Volcado con éxito
