### ISSUE TITLE
Testar el error cometido por el algoritmos

### ISSUE THREAD

**Issue by jlgarridol** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#54]
Utilizar los datos de conteo manuales generados con la aplicación desarrollada con ese fin, para testear el error que está cometiendo el algoritmo ante diferentes situaciones.

**Comment by Josemi** [comment]
Ayer no me dio tiempo a acabar el testeo asique lo he terminado hoy por la mañana aquí está el resultado:
Se ha desarrollado un test de integración que calcula el error relativo del algoritmo.
Para ello utiliza un conjunto de frames en formato jpg y un archivo txt en el que se han anotado manualmente el número de abejas en cada frame (número de frame == número de linea).
