### ISSUE TITLE
Implementar acceso a datos

### ISSUE THREAD

**Issue by Josemi** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#56]
.data

Package: .model
- Apiary: clase para modelar un colmenar.
- Hive: clase para modelar una colmena.
- Record: clase para modelar un registro de una grabación.

Package: .source
- ApiariesDataSource: (interfáz) punto de entrada principal para el acceso a los datos.
- ApiariesRepository: implementación concreta del data source para cargar los datos en caché.

Package: .source.local
- ApiariesLocalDataSource: implementación concreta del data source como base de datos SQLite. (No implementar de forma real todavía)
- ApiariesPersistenceContract: contrato usado por la base de datos para almacenar la información (nombre de las tablas y campos).
- ApiariesDbHelper: configuraciones específicas de la base de datos (nombre, creación, actualización...).

**Comment by Josemi** [comment]
Implementación realizada.

**Comment by jlgarridol** [comment]
Acabo de leer tu informe, no me acaba de convencer tu estructura de paquetes. Yo usaría otro subpaquete en source para que esté al mismo nivel que local, aunque sean interfaces

**Comment by edzlo** [comment]
Pues  a mí parece una estructura consistente, la de @Josemi , buen trabajo.

**Comment by MarinaGarme** [comment]
El informe es claro, la estructura de paquetes se entiende correctamente. No veo razón para que ha estás punto del proyecto se cambie el subpaquete.

**Comment by Josemi** [comment]
A estas alturas creo que no merece la pena cambiar la implementación ya que funciona perfectamente tal y como esta

**Comment by jlgarridol** [comment]
Ok, como veáis, si es así cerramos entonces la tarea
