### ISSUE TITLE
Procesar manualmente distintos fragmentos de vídeos

### ISSUE THREAD

**Issue by jlgarridol** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#58]

**Comment by jlgarridol** [comment]
Con los vídeos creados en #25 voy a intentar sacar concluciones de manera manual, una vez extraiga el algorimos se podrá integrar en la aplicación

**Comment by jlgarridol** [comment]
Marcha bien y casi tengo algo programable.

**Comment by jlgarridol** [comment]
Conclusiones tras la programación

### Case 1:

*   Extracto de #C14.
*   Actividad media, sombras de abejas y moscas.
*   Error: 2,43%

### Case 2:

-   Extracto de #C17.
-   Actividad media, cambios de iluminación y sombras de árboles.
-  Error: 0,89%

### Case 3:

- Extracto de #C5.
-   Alta actividad, solapamiento.
 -   Error: 4,48%

El error se encuentra en un rango aceptable. Principalmente causado por el solapamiento. El error de solapamiento se verá reducido tras el procesamiento de la señal que se hará en la fase posterior.

**Comment by edzlo** [comment]
Buen trabajo.
