### ISSUE TITLE
Elegir herramienta de documentación

### ISSUE THREAD

**Issue by Josemi** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#6]
Elección de la herramienta para la documentación del proyecto

**Comment by jlgarridol** [comment]
También podemos usar un foro para las discusiones en diferido, he leído que eso se usa cada vez más

**Comment by Josemi** [comment]
Para hacer la documentación yo elegiría o LibreOffice o LaTeX si queremos empezar y practicar con esta herramienta

**Comment by edzlo** [comment]
En mi opinión LibreOffice, pues lo sabemos utilizar todos.

**Comment by Josemi** [comment]
Usaremos LibreOffice como herramienta de documentación
