### ISSUE TITLE
Automatizar exportación de md a pdf

### ISSUE THREAD

**Issue by Josemi** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#67]
Automatizar exportación de md a pdf: http://pandoc.org/

**Comment by jlgarridol** [comment]
Algo ligerito antes de cerrar, no creo que tarde tanto

**Comment by jlgarridol** [comment]
Lo he integrado en readthedocs. En cada commit se genera un pdf con la última versión de la documentación en:

https://media.readthedocs.org/pdf/go-bees/latest/go-bees.pdf

*Las imágenes no se cargan.

**Comment by jlgarridol** [comment]
No pude terminarlo anoche por culpa de las imágenes. Ya lo he solucionado

Ya se insertan correctamente las imágenes y las fórmulas matemáticas se renderizan directamente del código (ya no hace falta pasarlas a imágenes).
