### ISSUE TITLE
Búsqueda bibliográfica de artículos

### ISSUE THREAD

**Issue by MarinaGarme** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#7]
Articulos interesantes o relacionados con el proyecto

**Comment by MarinaGarme** [comment]
Búsqueda de artículos especializados en las aplicación de la biblioteca, con Ubucat

**Comment by jlgarridol** [comment]
Alguno interesante?

**Comment by jlgarridol** [comment]
He estado leyendo lo que pasaste y muy interesante, dejo la tarea como cerrada
