### ISSUE TITLE
Cambiar ListView por RecyclerView

### ISSUE THREAD

**Issue by Josemi** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#77]
The RecyclerView is much more powerful, efficient, flexible and a major enhancement over ListView.

**Advantages**

- ViewHolder Pattern
- LayoutManager
- Item Animator
- Item Decoration
- OnItemTouchListener

**Disadvantages**

- It is way more complex than a list view.

**Comment by edzlo** [comment]
![image](https://user-images.githubusercontent.com/25634633/32968828-0190be26-cbe3-11e7-852b-42c0a813f197.png)
