### ISSUE TITLE
Crear vista para no colmenares/colmenas/grabaciones

### ISSUE THREAD

**Issue by edzlo** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#81]
Crear una vista para que se muestre cuando no hay ningún colmenar, ninguna colmena o ninguna grabación.

**Comment by jlgarridol** [comment]
Gracias a lo que aprendí de MVP me pongo a ello

**Comment by jlgarridol** [comment]
Gracias a lo que aprendí de MVP me pongo a ello

**Comment by jlgarridol** [comment]
Vista creada, aunque no funcionará por si misma hasta que el presentador y el modelo estén bien definidos
