### ISSUE TITLE
Márgenes y paddings mal puestos en las listas

### ISSUE THREAD

**Issue by edzlo** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#85]
Al desplazar la lista los elementos se cortan en los márgenes establecidos no al llegar al elemento padre.

Solución:
http://stackoverflow.com/questions/17920492/adding-bottom-margin-to-listview-last-element/

**Comment by jlgarridol** [comment]
Ya os dije en la oficina que los listview darían más problemas que soluciones, yo apostaría para evitar el problema utilizar constraintview antes que arreglar algo que siempre estuvo roto y va a dar luego más problemas

**Comment by MarinaGarme** [comment]
El link explica bien como arreglar los márgenes y paddings, deberíamos utilizarlo

**Comment by Josemi** [comment]
Creo que en la discusión del otro día quedó bastante claro, los constraintview necesitan demasiados recursos, por lo que en nuestro caso nos viene mejor los listviews

**Comment by edzlo** [comment]
Resolveré el bug con los listview.

**Comment by jlgarridol** [comment]
Vengaaaaa, acepto la derrota.
