### ISSUE TITLE
Prototipo inicial de la app

### ISSUE THREAD

**Issue by MarinaGarme** [MarinaGarme/GESPRO_PracticaGestionTareas_1718#9]
Realizar un prototipo de la interfaz gráfica de la app.

**Comment by MarinaGarme** [comment]
![bed9edac-779f-11e6-9fbf-8cd4cfefff32 2](https://user-images.githubusercontent.com/33252929/32489938-c5c904f4-c3b1-11e7-967d-f7dbfdef0373.jpg)

**Comment by jlgarridol** [comment]
Tiene buena pinta. Lo paso a review
